const path = require('path');
const fs = require('fs');
console.log('execPath', process.execPath);
const execDir = path.dirname(process.execPath);
console.log('execDir', execDir);
console.log('node.exe exists in execDir:', fs.existsSync(path.join(execDir, 'node.exe')));
console.log('current dir', process.cwd());
console.log('PATH includes out/main:', process.env.PATH && process.env.PATH.split(path.delimiter).includes(path.join(__dirname, 'out', 'main')));
console.log('PATH includes electron dist:', process.env.PATH && process.env.PATH.split(path.delimiter).includes(execDir));
process.exit(0);